title: Andrij Stachurski
description: Andrij Stachurski is a technical consultant and front-end web developer from Canberra, Australia
keywords: Andrij Stachurski, Web, CSS, JavaScript, HTML5, Front-end, Web Developer, Sys Admin, Systems Administrator, Australia, Canberra

timezone: Australia/Sydney
google_analytics: UA-57206412-1

baseurl: /

sass:
   sass_dir: /assets/sass
   style: :compressed

repository: 

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"